### PR TITLE
Optimisation

### PR DESCRIPTION
**Pull request by evignola**
Hi Michail,
This is my first attempt to optimise the code. The code has sped up a bit, but the improvement in speed is not very important. The "sigma" procedure has now made the correlation function procedure and the equation data structure obsolete; it saves a few loops the way we discussed yesterday, but the procedure is called every time "funcv" is called, which forces the calculation of the energy vector and of the partition loops (this is time consuming). So, maybe this is not what you had in mind.

### CODE REVIEW

**Comment by evignola** [comment]
Let me add that I have just tested the K2NNC2 and calculation takes 30 mins versus 4 hs of the non-optimised version.

**Comment by mstamatakis** [comment]
30 min compared to 4 hrs, that's a factor of 8, hardly "not very important" speedup. We can still do better in terms of speed and source code architecture. Right now you have hard-coded the residuals of each approximation, not using at all the lhs and rhs members of the class. You want to have a general subroutine (call it calculate_residuals or something) which gives you the residuals for any approximation given only the instantiated datastructure (without having to hard code anything).


You also add a term in your equation data-structure that gives you the number of equations you have:

```
    type :: equation
     integer neqns
     integer, allocatable, dimension(:,:) :: lhs
     integer, allocatable, dimension(:,:) :: rhs 
    end type 
```
Then you should write general loops that use these fields in the subroutine calculating the residuals, e.g. loop from 1 to appr%eqn%neqns, calculate the relevant correlation functions in the loop and take the difference of their logs.

**Comment by mstamatakis** [comment]
Also, I see you keep filtering out zeros in your loops, e.g. in the energy function:

```
    do i=1,nrows
     s=1
     do j=1,nsites
      if(appr%hamilt%orig%term(i,j).ne.0) then
       s=s*state(appr%hamilt%orig%term(i,j))
      end if
     end do
     energy=energy+s*appr%hamilt%orig%value(i)
    end do
```

This is time consuming as I have pointed out before: in your loop you have to go through all entries, even the zero ones, thereby repetitively performing useless operations. Also, loops with if clauses don't optimise well, see:

https://jblevins.org/log/efficient-code
https://blogs.sas.com/content/iml/2012/02/13/avoid-unnecessary-if-then-statements-in-loops.html

My understanding is that right now you have the general class-wide parameter nrows for the number of terms. This should not be a class-wide parameter, because each approximation has its own number of terms. Instead you should have appropriate fields in the "original" and "correction" datastructures. You should add one integer field that stores the number of "original" and "correction" terms in the Hamiltonian, and one field that tells you how many elements in term are non-sero (i.e. what interaction term you are "reading" in that line, 1-body, 2-body, etc) e.g.:

```
    type :: original
     integer nterms
	 integer, allocatable, dimension(:) :: nsitesinter
     integer, allocatable, dimension(:,:) :: term
     real*8, allocatable, dimension(:) :: value 
    end type 
```

Then you should make your loops use these fields, e.g. loop from 1 to appr%hamilt%orig%term%nsitesinter() and get rid of the if clauses:


```
    do i=1,appr%hamilt%orig%term%nterms
     s=1
     do j=1,appr%hamilt%orig%term%nsitesinter(i)
      s=s*state(appr%hamilt%orig%term(i,j))
     end do
     energy=energy+s*appr%hamilt%orig%value(i)
    end do
```

You can populate the field appr%hamilt%orig%term%nsitesinter once and for all, in the subroutine that initialises each approximation. You can use a loop that counts the non-zero entries (like you are doing now) but only once, so that you avoid repetitive operations.

Please let me know if the above two comments make sense.

**Comment by evignola** [comment]
"You also add a term in your equation data-structure that gives you the number of equations you have"
    At the moment, this is done by the class-wide variable "npar". We could make it class-specific, if you 
    show me the real advantage to do so. At the moment, "npar" works perfectly. Maybe you want to do 
    so to make the variable accessible to the class only... but I would not know.

**Comment by mstamatakis** [comment]
Yes, please remove the npar and nrows, and have fields in the class that give you the number of parameters (= number of equations) and the number of terms. The advantage is that each instantiated class object will "encode" a specific approximation, and different approximations have different numbers of parameters and numbers of terms. So you can later develop a main program that instantiates e.g. 7 approximations and solves all of them in parallel, without conflicts...

**Comment by evignola** [comment]
Ah, in this case, I also put "nsites" as integer field of type "approximation_type".

**Pull request merged**
